# **THIS NEEDS TO BE RUN FROM ROOT DIRECTORY, OTHERWISE IT CANT ACCESS POETRY FILES!!!**
from docker.io/python
# from mcr.microsoft.com/playwright/python:v1.40.0-jammy

run pip install poetry

workdir /e2e/

copy pyproject.toml poetry.lock /e2e/

run poetry install --no-root --no-directory

run poetry run playwright install --with-deps

copy playwright_scrape/*.py /e2e/

run poetry install --no-root

cmd ["poetry", "run", "pytest"]
