version: '3.0'
services:
  db:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: WeatherData
    networks:
      - data_literacy_network
    ports:
      - 3306:3306
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - data_literacy_network

  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.app
    volumes:
      - ../project:/project
    networks:
      - data_literacy_network


networks:
  data_literacy_network:
    name: data_literacy_network
    external: true