- "studies/29_01_2024_fig_LD_accuracy.ipynb" 
- "studies/29_01_2024_fig_LD_correlation_matrix.ipynb" 
- "studies/29_01_2024_fig_LD_raw_data.ipynb" 
- "studies/29_01_2024_fig_LD_trend.ipynb"
- "studies/11_01_24_LD_fig_BaWu_stations.ipynb"